global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'simple_http_sentence'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']