name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # You can adjust this to match your Go version

    - name: Install dependencies
      run: |
        cd app
        go mod download

    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger docs
      run: |
        cd app
        swag init

    - name: Run tests
      run: |
        cd app
        go test -v ./...

    - name: Run vet
      run: |
        cd app
        go vet ./...

    - name: Run Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
        working-directory: ./app